### ISSUE TITLE
Dictionary completion failed with error.

### ISSUE THREAD

**Issue by wxguy** [Kaiser-Yang/blink-cmp-dictionary#14]
Installed LazyVim and enabled blink from LazyExtras. All plugins are up to date. 

Here is the `~/.config/nvim/lua/plugins/blink-cmp.lua` content:-

```
return {
  "saghen/blink.cmp",
  event = { "InsertEnter", "CmdlineEnter" },
  dependencies = {
    "rafamadriz/friendly-snippets",
    "xzbdmw/colorful-menu.nvim",
    "Kaiser-Yang/blink-cmp-dictionary",
    dependencies = { "nvim-lua/plenary.nvim" },
  },
  version = "*",
  ---@module 'blink.cmp'
  ---@type blink.cmp.Config
  opts = {
    keymap = {
      preset = "enter",

      ["<Tab>"] = { "snippet_forward", "select_next", "fallback" },
      ["<S-Tab>"] = { "snippet_backward", "select_prev", "fallback" },
      ["<C-CR>"] = { "cancel" },
    },
    appearance = { use_nvim_cmp_as_default = true },
    completion = {
      documentation = {
        auto_show = true,
        auto_show_delay_ms = 250,
        treesitter_highlighting = true,
        window = {
          border = "rounded",
        },
      },

      menu = {
        border = "rounded",

        draw = {
          columns = { { "kind_icon" }, { "label", gap = 1 } },
          components = {
            label = {
              text = function(ctx)
                return require("colorful-menu").blink_components_text(ctx)
              end,
              highlight = function(ctx)
                return require("colorful-menu").blink_components_highlight(ctx)
              end,
            },
          },
        },
      },
    },
  },
  opts_extend = { "sources.default" },
}

```

and now wanted to configure blink-dict. Here is the content of `~/.config/nvim/lua/plugins/blink-cmp-dict.lua`:-

```
return {
  {
    "saghen/blink.cmp",
    dependencies = {
      {
        "Kaiser-Yang/blink-cmp-dictionary",
        dependencies = { "nvim-lua/plenary.nvim" },
      },
    },
    opts = {
      completion = {
        accept = {
          auto_brackets = {
            enabled = false,
          },
        },
      },
      sources = {
        -- default = { "dictionary", "lsp", "path", "luasnip", "buffer" },
        default = { "dictionary" },
        providers = {
          dictionary = {
            module = "blink-cmp-dictionary",
            name = "Dict",
            min_keyword_length = 2,
            max_items = 8,
            score_offset = -100,
            opts = {
              dictionary_files = {
                "~/.config/nvim/dict/words.txt",
              },
            },
          },
        },
      },
    },
  },
}
```

When I opened a markdown file and started typing, I get following error:-

```
"get_completions failed" "\n" with error code: 1 
```

Actually, I don't know how to view full error log. Let me know if any other information is required.

Dictionary source is important for my workflow. Kindly help to resolve the issue.

**Comment by Kaiser-Yang** [comment]
Fixed in the lates commit on master.

**Comment by wxguy** [comment]
Apologies to post on the closed issue. But the issue is not solved. I am now not getting both error message and suggestions.

**Comment by Kaiser-Yang** [comment]
Do you update? I use the default configuration, and just configure the dictionary_file, it works fine:

![Image](https://github.com/user-attachments/assets/05fb4d2c-8dd7-408a-9864-92ed6d6d4767)

**Comment by wxguy** [comment]
Yes I did with command `nvim --headless "+Lazy! sync" +qa` and got following output with respect to your plugin.

```
[blink-cmp-dictionary] checkout | HEAD is now at 4842221 chore: default hl for icons
```

which is matching with your last commit. 

I copied default config from your readme file and now I get following error:

```
Error executing lua callback: ...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:82: Luasnip has been moved to the `snippets` source, alongside a new preset system (`snippets.preset = 'luasnip'`). See the documentation for more information.
```

```
Error detected while processing TextChangedI Autocommands for "*":
```

```
stack traceback:
	[C]: in function 'error'
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:82: in function 'get_provider_by_id'
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:73: in function 'get_enabled_providers'
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:107: in function 'get_trigger_characters'
	...lazy/blink.cmp/lua/blink/cmp/completion/trigger/init.lua:169: in function 'is_trigger_character'
	...lazy/blink.cmp/lua/blink/cmp/completion/trigger/init.lua:54: in function 'on_char_added'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:53: in function <.../nvim/lazy/blink.cmp/lua/blink/cmp/lib/buffer_events.lua:43>
```

Then reverted back to above dict config and no message or completion.

**Comment by Kaiser-Yang** [comment]
You update your `blink.cmp`, so you should reference the lated documentation of `blink.cmp` and to do some new configuration for `snippets`.

**Comment by wxguy** [comment]
Ahhhh. Fond the issue. I was using the `relative path` to words.txt file like below as I cloned the LazyVim to different location for testing:-

```
dictionary_files = { "../../dict/words.txt"}
```

which did not work. Neither the below path:-

```
dictionary_files = { vim.fn.expand("../../dict/words.txt") }
```

The working path is:

```
dictionary_files = { "~/.config/nvim/dict/words.txt"}
```

or

```
dictionary_files = { "/home/sundar/.config/nvim/dict/words.txt"}
```

If the above info is true, you may wish to update your `README` file accordingly.
